[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name= "Ergo"
version = "0.1.0"
dependencies = [
    "PySide6>=6.10",
]

[project.scripts]
ergo = "app.main:main"
